export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_CART = 'FETCH_CART';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const TOTAL_INCREASE = 'TOTAL_INCREASE';
export const TOTAL_INCREASE_SUCCESS = 'TOTAL_INCREASE_SUCCESS';
export const TOTAL_INCREASE_FAILURE = 'TOTAL_INCREASE_FAILURE';

export const TOTAL_DECREASE = 'TOTAL_DECREASE';
export const TOTAL_DECREASE_SUCCESS = 'TOTAL_DECREASE_SUCCESS';
export const TOTAL_DECREASE_FAILURE = 'TOTAL_DECREASE_FAILURE';
